### ISSUE TITLE
Question about versioning/release strategy

### ISSUE THREAD

**Issue by sgblv** [kubermatic/machine-controller#1025]
I have a question, which version of the product maintainers consider as stable and what is release strategy. I am bit confused  because 1.27.11 is latest now but 1.32.1 and 1.33.0 also exist.

**Comment by kron4eg** [comment]
usually the latest (highest) release is considered stable, but we also have maintain old relesas branched and backport different fixed from the tip to those release branches. This is due to the fact that our [KKP](https://github.com/kubermatic/kubermatic) releases has support periods and machine-controller version is strictly hardcoded in the KKP.

Bottom line is: older machine-controller release branches sometimes get occasional updates when we require them in the upstream KKP.
