### ISSUE TITLE
[Bug] Dont't allow uppercase names for Machine Deployments

### ISSUE THREAD

**Issue by Schluggi** [kubermatic/machine-controller#1126]
Hi,

both forms for adding a new Machine Deployment seems to have a bug while checking the name.

When i try to use special chars in the Machine Deployment name this message appears:
![image](https://user-images.githubusercontent.com/43608073/144983049-7f6a04aa-7081-4c8f-a75b-87b12b976985.png)

Alright. So as the message says in the brackets (the text in front of is also wrong) only lowercase chars, digits and dashes are allowed. But the message disappears if i remove the exclamation mark at the end.
![image](https://user-images.githubusercontent.com/43608073/144983091-911459bf-311e-4a93-b9cb-d607649ad37c.png)

And ... the Machine Deployment fails.
![image](https://user-images.githubusercontent.com/43608073/144985323-99680346-ef24-400f-a232-8a853d5ec48b.png)

So please fix the name check :)
Thanks.

**Comment by embik** [comment]
Hi @Schluggi, that sounds like https://github.com/kubermatic/kubermatic/issues/8301 to me, right? machine-controller isn't really the source of the bug here, as the validation is happening correctly in machine-controller (which is the problem, as the UI and machine-controller disagree on what's allowed).

**Comment by Schluggi** [comment]
@embik yes. It's duplicated. Sorry for that :/

**Comment by embik** [comment]
No worries at all!
