### ISSUE TITLE
Drop leader lease on shutdown

### ISSUE THREAD

**Issue by alvaroaleman** [kubermatic/machine-controller#146]

**Comment by mrIncompetent** [comment]
Could you be a bit more precise?
The lease should run out when the controller is not updating the timestamp, or?

**Comment by alvaroaleman** [comment]
Yes it runs out, but it is valid for 15 seconds and gets renewed every two seconds, meaning there is a 13 to 15s interval after a deployment got updated until leader election even starts.

It would be much nicer if the machine-controller could instead drop its lease on shutdown.

**Comment by mrIncompetent** [comment]
In what real-world scenarios is this relevant?
I would rather keep it simple. Its a controller and it's not doing time critical work

**Comment by alvaroaleman** [comment]
Well its pretty annoying when testing out stuff, as it increases the duration of the feedback loop. I was hoping this is gonna be an easyfix :)

**Comment by kdomanski** [comment]
I looked into k8s/client-go code and there doesn't seem to be any facilities to drop the lease - it's just supposed to expire.

On the other hand, in the context of testing out new builds of machine-controller, the expiry doesn't even matter, since the client is checking for the last time an election record was seen, and not it's actual age. https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L269

In other words, #264

**Comment by mrIncompetent** [comment]
So this can be closed in favor of #264 ?

**Comment by kdomanski** [comment]
Unless we want to add explicit lease drop to the client. #264 is a separate, but bigger issue.
