### ISSUE TITLE
CentOS: Use docker yum repository

### ISSUE THREAD

**Issue by cbeneke** [kubermatic/machine-controller#460]
The provision path for centOS installs docker in version 1.13.1 (w/ backports). As Docker provides a yum repo for current docker images (https://docs.docker.com/install/linux/docker-ce/centos/), these should be used instead.

Opinions?

**Comment by alvaroaleman** [comment]
I am not in favor of this. RedHat has a heavily patched Kernel in RHEL7/Centos7 that includes an overlay2 driver (Which upstream kernel has since 4.00 I believe). I would prefer to stick to the RH-Maintained docker in order to be sure that there are no incompatibilities or other weird behavior.

What is the reason you are asking for this?

**Comment by cbeneke** [comment]
We observed some problems with the docker daemon on some centOS clusters (didn't spend too much time debugging, and it was quite random: 1-3 nodes not starting the daemon without an actual error in a 30 node cluster). Experience wise the repos from the vendor are often better maintained than the upstream repos (which might not hold for centOS and/or a heavily used packet like docker is), so we thought a switch might help.
I couldn't test too well so far if there are problems with the 18.09 version, but I couldn't reproduce the problems described above on it (might not be related). The patched kernel we didn't had in mind so far though^^

**Comment by bashofmann** [comment]
We discussed it and agreed that it's better to stay with the RH maintained version. This issue and the PR can be closed then.
