### ISSUE TITLE
Hetzner: Auto assign FloatingIP to a working node

### ISSUE THREAD

**Issue by farodin91** [kubermatic/machine-controller#572]
I'm trying to assign automatically a FloatingIP. 
**Current state:**
I was able to add a floating ip manually to worker node.

**Goal:**
My goal is to use the FloatingIP as a entry point into my cluster and use it in combination with traefik to have own builded ingress with static ip.

PS: I'm using currently kubeone to create my kubernetes cluster. 
I would like to help to get this feature implemented.

**Comment by alvaroaleman** [comment]
Hi,

Thanks for your inquiry. Adding a floating IP to a node is in no circumstances a requirement for this node to be a functioning member of a Kubernetes cluster since Hetzner does not offer any kind of SDN. Thus, your request is out of scope for this project. 


What you actually seem to want is a Loadbalancer controller that uses Floating IPs to realize these Loadbalancers. If such a project doesn't exist yet, I recommend using [Kubebuilder](https://github.com/kubernetes-sigs/kubebuilder) to build it yourself.
