### ISSUE TITLE
Unable to list KubeVirt machine deployments after upgrade from MC 1.19 (KKP 2.15) to 1.23.1 (KKP 2.16)

### ISSUE THREAD

**Issue by mfranczy** [kubermatic/machine-controller#903]
As mentioned in the title, the error:
```
Error 500failed to output machine deployment nervous-shirley: failed to get node cloud spec from machine deployment: failed to parse kubevirt config: json: cannot unmarshal string into Go struct field RawConfig.dnsConfig of type v1.PodDNSConfig
```

**Comment by moadqassem** [comment]
So the reason of why this shows up is due to the structure that we used for the dns configurations. DNS configs were part of the datacenter which was read from a chart so we had as set to be as a string. After we moved our datacenter configurations to the Seed CR we changed that to be marshalled from the `k8s.io/api/core/v1.PodDNSConfig` type. Thus I guess we can simply close this ticket.
