### ISSUE TITLE
cloud-init customization

### ISSUE THREAD

**Issue by hrenard** [kubermatic/machine-controller#921]
Hi,

I'm considering KubeOne to deploy a new cluster, but I don't fully trust Hetzner private network and I wanted to use Calico with WireGuard enabled. So I need to install wireguard package on each node, the easiest way  would be to add it directly in the cloud-init. But if I'm not mistaken there is currently no way to customize the cloud-init produced by the machine-controller. 

Is this a feature that you would consider adding in the future ? What do you currently recommend in such situation ?

**Comment by kron4eg** [comment]
We are currently working on the alternative to our static-ish userdata generation, that will allow users to customize cloud-init, unfortunately it's still closed (just because it's not yet ready for the prime-time).

But for now you should use custom image with preinstalled wireguard.

**Comment by teksuo** [comment]
Hi there, 

I'm assuming this is still not possible?

**Comment by embik** [comment]
@teksuo it's actually possible, latest releases of KubeOne and KKP come with OSM (Operating System Manager) enabled by default. That allows you to create custom profiles with customized cloud-init data. See [our documentation](https://docs.kubermatic.com/kubermatic/v2.21/tutorials-howtos/operating-system-manager/) for a start.

**Comment by teksuo** [comment]
Thank you so much for your quick response.

After doing some testing we have encountered that in order to add our custom configuration on top of the default OSP ('osp-ubuntu' in our case), we had to manually extract that default OSP and merge our configuration into it after escaping the templating stuff. I don't know if there is a better way of doing this, but that's how we did it.

Now our problem is that we wanted to access a secured API in order to download the actual script we want to run. For this we would need to pass some kind of bootstrap token to it like the ones used by the default OSP ({{ .Token }}, {{.CloudProviderName}}, and so on. We are trying to figure out where this values come from, but we don't see them in any ServiceAccount or Secret. 

Could you clarify a little bit more how this should be done? thanks in advance

**Comment by embik** [comment]
@teksuo I general you shouldn't update the default OSPs but create your own (you can base it on the defaults though), but maybe I misunderstood that first part.

Can you please raise your question over at https://github.com/kubermatic/operating-system-manager so that people having the same question can better discover it? As a matter of fact, the actual script applied on a node with OSM enabled is already downloaded from a secured API (the Kubernetes API of your cluster), so that might be enough for your use-case? If so, just adding the script itself directly to the OSP would do the trick.
